/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2022-04-01

The MIT License (MIT)
Copyright (c) 2019 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include <stddef.h>
#include "stm32f10x.h"
#include "declarations.h"


/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/
int main(void)
{

  /******************************************************
  	 *
  	 *                    UART Configuration
  	 *
  	 * *****************************************************/

  	/*Enables USART1 clock and port A clock*/
  	RCC->APB2ENR |= RCC_APB2ENR_USART1EN | RCC_APB2ENR_IOPAEN;

  	/*Enables the input and output in the bit 9 on port A*/
  	GPIOA->CRH |= GPIO_CRH_MODE9 | GPIO_CRH_CNF9_1;
  	GPIOA->CRH &= ~(GPIO_CRH_CNF9_0);

  	/*
  	 * Enables UART = Set UE bit
  	 * Transmit enable = Set TE bit
  	 * Enables Transmission interrupt = Set TXEIE bit
  	 * */
  	USART1->CR1 |= USART_CR1_UE | USART_CR1_TE | USART_CR1_TXEIE;

  	/*Enables the global interruption to UART in NVIC*/
  	NVIC->ISER[1] = NVIC_ISER_SETENA_5;

  	/*Sets the baudrate in 9600 Baudios*/
  	USART1->BRR = 0x1D4C;

  	/******************************************************
  	 *
  	 *               ADC Configuration
  	 *
  	 * ****************************************************/
  	/*Enables the clock in the ADC1 and in the port C*/
  	RCC->APB2ENR |= RCC_APB2ENR_ADC1EN | RCC_APB2ENR_IOPCEN | RCC_APB2ENR_AFIOEN;

  	/*Enables the ADC Global interrupt in the NVIC*/
  	NVIC->ISER[0] = NVIC_ISER_SETENA_18;

  	/*Enable the prescaler with a value of 6*/
  	RCC->CFGR |= RCC_CFGR_ADCPRE_1;

  	/*Select 1 conversion in the regular group*/
  	ADC1->SQR1 &= ~(ADC_SQR1_L);

  	/*Select first conversion the channel 0*/
  	ADC1->SQR3 &= ~(ADC_SQR3_SQ1);

  	/*Configures Channel 0 as Analog input*/
  	GPIOA->CRL &= ~(GPIO_CRL_CNF0);
  	GPIOA->CRL &= ~(GPIO_CRL_MODE0);

  	/*Enables the interrupt at the end of conversion*/
  	ADC1->CR1 |= ADC_CR1_EOCIE;

  	/*Power on the ADC the first time to wake up from the Power Down Mode*/
  	ADC1->CR2 |= ADC_CR2_ADON;
  	for (int i = 0; i < 50; i++)
  	{}
  	/*Power on the ADC by at least 2 cycles*/
  	ADC1->CR2 |= ADC_CR2_ADON;
  	for (int i = 0; i < 50; i++){}

  	/*Calibrate the ADC*/
  	ADC1->CR2 |= ADC_CR2_CAL;
  	for (int i = 0; i < 50; i++){}

  	/*************************************************************
  	 *
  	 *                  TIMER2 SETUP
  	 *
  	 * ************************************************************/

  	/*Enables the TIM2*/
	RCC->APB1ENR |= RCC_APB1ENR_TIM2EN;
	/* Preload value to counter*/
	TIM2->ARR = 0X0FFF;
	/*the value to preescaler*/
	TIM2->PSC = 0X0FFF;
	/*Enables the interrupt when update occurs*/
	TIM2->DIER |= TIM_DIER_UIE;
	/*Enables interrupt to TIM2*/
	NVIC->ISER[0] = NVIC_ISER_SETENA_28;
	/*Enables counter*/
	TIM2->CR1 |= TIM_CR1_CEN;
  	/*Pin13 PortC output pull down*/
  	GPIOC->CRH |= GPIO_CRH_MODE13_0;
  	GPIOC->CRH |= GPIO_CRH_CNF13_0;
//
  	USART1->DR = 'I';

  /* TODO - Add your application code here */

  /* Infinite loop */
  while (1)
  {
//	  for(int i = 0; i<= 5000000; i++);
//	  GPIOC->ODR ^= (1<<13);
//	  if(USART1->SR & USART_SR_TXE){
//		  USART1->DR = input;
//	  }
  }
}

